### ISSUE TITLE
Typo in detailed balance?

### ISSUE THREAD

**Issue by jonnyroutley** [rsettlage/rsettlage.github.io#1]
Hi, 

In [this page](https://rsettlage.github.io/mcmc/2022-06-13-detailed-balance-proof-tldr/), should equations 1 and 2 be y' ~ f(y' | x) and x' ~ (x' | y') to be consistent with equation 4? Just below this as well backward is spelt bacward. Otherwise thank you very much!

Jonny

**Comment by rsettlage** [comment]
Thanks for the spelling typo!

For the question, I think it is correct as written.  For equations 1 and 2, these are sequential, so given (x,y), you draw a y' (so this is y' ~ f(x,y) ), now given this new y', you draw a x' given the (x,y'), (so this is x' ~ f(x,y`) ).

In the right hand side of line one of equation 4, we could instead write it as f(x,y)f(y'|x,y)f(x'|x,y').  But, we are assuming no memory, so can simplify.
